[[constraint]]
  name = "github.com/StackVista/stackstate-agent"
  revision = "4bff1c1cc2aaec39eb753d831d483eaacfb2deda"

[[constraint]]
  name = "github.com/DataDog/gopsutil"
  revision = "771928d86fa878b9d62f073a7a6f91ee0a358105"

[[constraint]]
  name = "github.com/StackVista/tcptracer-bpf"
  revision = "dd10e1ac736a5bf240ba785c16a6a50a933cb9af"

[[constraint]]
  name = "github.com/DataDog/sketches-go"
  source = "github.com/StackVista/sketches-go"
  version = "=v1.1.0"

[[constraint]]
  name = "github.com/DataDog/zstd"
  revision = "2bf71ec4836011b92dc78df3b9ace6b40e65f7df"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "=v1.3.1"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "=v2.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.2.2"

[[constraint]]
  name = "golang.org/x/sys"

[[override]]
  name = "gopkg.in/yaml.v2"
  revision = "d670f9405373e636a5a2765eea47fac0c9bc91a4"

[[override]]
  name = "github.com/mailru/easyjson"
  version = "=v0.7.7"
