[[constraint]]
  name = "github.com/DataDog/datadog-agent"
  revision = "020e0e819623b29ca1d36ec7e39ed4c2186ce635"

[[constraint]]
  name = "github.com/DataDog/gopsutil"
  revision = "771928d86fa878b9d62f073a7a6f91ee0a358105"

[[override]]
  name = "github.com/CharlyF/custom-metrics-apiserver"
  revision = "56ec6921a4cfec971e5a8c89d5f4629c17cbb21a"

[[constraint]]
  name = "github.com/DataDog/tcptracer-bpf"
  revision = "636ee01a99a4bd352329de98f40fb9fdf611d1c9"

[[constraint]]
  name = "github.com/DataDog/zstd"
  revision = "2bf71ec4836011b92dc78df3b9ace6b40e65f7df"

[[constraint]]
  name = "github.com/go-ini/ini"
  revision = "d3de07a94d22b4a0972deb4b96d790c2c0ce8333"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "d76fbc1373015ced59b43ac267f28d546b955683"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "golang.org/x/sys"
