[[constraint]]
  name = "github.com/DataDog/datadog-agent"
  revision = "bd4943d0a5d51bce4e43b7e86a2cab7076a543e1"

[[constraint]]
  name = "github.com/DataDog/gopsutil"
  revision = "c8f74f1344dd41bc49ec4d3c2377c526aaedfd20"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "d76fbc1373015ced59b43ac267f28d546b955683"

[[constraint]]
  name = "github.com/iovisor/gobpf"
  revision = "3b07770c6d5e2bd37e582ecd49460e6ef094f257"

[[constraint]]
  name = "github.com/mailru/easyjson"
  revision = "60711f1a8329503b04e1c88535f419d0bb440bff"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "golang.org/x/sys"

[[override]]
  name = "github.com/kardianos/osext"
  revision = "ae77be60afb1dcacde03767a8c37337fad28ac14"

[[override]]
  name = "bitbucket.org/ww/goautoneg"
  source = "github.com/adjust/goautoneg"
  revision = "d788f35a0315672bc90f50a6145d1252a230ee0d"
