[[constraint]]
  name = "github.com/DataDog/datadog-agent"
  revision = "daf74af72a86be259561ce25c277a3d7a8d72830"

[[constraint]]
  name = "github.com/DataDog/gopsutil"
  revision = "771928d86fa878b9d62f073a7a6f91ee0a358105"

[[constraint]]
  name = "github.com/DataDog/tcptracer-bpf"
  revision = "e67093561a9e7e3cd7380d68d5022a1626ce32b2"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "d76fbc1373015ced59b43ac267f28d546b955683"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "golang.org/x/sys"
