[[constraint]]
  name = "github.com/StackVista/stackstate-agent"
  revision = "bcfb39d79bc7cd7ad5742b6d62837062af8d62a9"

[[constraint]]
  name = "github.com/DataDog/gopsutil"
  revision = "771928d86fa878b9d62f073a7a6f91ee0a358105"

[[constraint]]
  name = "github.com/StackVista/tcptracer-bpf"
  revision = "8db9a7ee3eb6be09daeb6c32d8a0d367297aae51"

[[constraint]]
  name = "github.com/DataDog/zstd"
  revision = "2bf71ec4836011b92dc78df3b9ace6b40e65f7df"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "d76fbc1373015ced59b43ac267f28d546b955683"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "=v2.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.2.2"

[[constraint]]
  name = "golang.org/x/sys"

[[override]]
  name = "gopkg.in/yaml.v2"
  revision = "d670f9405373e636a5a2765eea47fac0c9bc91a4"
