#!/bin/sh
### BEGIN INIT INFO
# Provides:          stackstate-process-agent
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: process-agent
# Description:       An agent that collecting and submitting process data to StackState
### END INIT INFO

# Author: DataDog, Inc <package@datadoghq.com>
# Author: StackState <info@stackstate.com>

# source functions library
. /lib/lsb/init-functions

PATH=$PATH:/sbin
PIDFILE=/opt/stackstate-process-agent/run/stackstate-process-agent.pid
DAEMON=/opt/stackstate-process-agent/bin/stackstate-process-agent
CONFIG=/etc/stackstate-agent/stackstate-process-agent.ini
export STS_PROCESS_AGENT_ENABLED=true

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

start() {
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
        echo 'stackstate-process-agent already running' >&2
	return 1
    fi
    echo 'Starting stackstate-process-agent...' >&2
    start-stop-daemon --start --quiet --oknodo --background \
        --make-pidfile --pidfile $PIDFILE --chuid stackstate-agent \
        --startas /bin/bash -- -c \
        "exec $DAEMON -config=$CONFIG >> /var/log/stackstate-process-agent.log 2>&1"
}

stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo 'stackstate-process-agent not running' >&2
	return 1
    fi
    echo "Stopping stackstate-process-agent..." >&2
    start-stop-daemon --stop --retry 30 --quiet --oknodo --pidfile $PIDFILE && rm -f $PIDFILE
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$DAEMON" stackstate-process-agent
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"

esac
