version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    environment:
      - GODIST: "go1.10.1.linux-amd64.tar.gz"
      - GOPATH: /home/circleci/project/.go_workspace
      - BASH_ENV: /home/circleci/project/.bashrc
    steps:
      - checkout
      - run: touch $BASH_ENV
      - run: echo 'export IMPORT_PATH=$GOPATH/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV && source $BASH_ENV
      - run: sudo apt-get update && sudo apt-get -y install linux-headers-$(uname -r) rsync rake
      - run: mkdir -p $GOPATH $GOPATH/bin $IMPORT_PATH download
      - run: test -e download/$GODIST || curl -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
      - run: sudo tar -C /usr/local -xzf download/$GODIST --mode='a+rwX'
      - run: rsync -azC --delete ./ $IMPORT_PATH
      - run: curl https://glide.sh/get | sh
      - run: cd $IMPORT_PATH && rake ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
