version: 2

references:

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    environment:
      - GODIST: "go1.10.1.linux-amd64.tar.gz"
      - GOPATH: /home/circleci/project/.go_workspace
      - BASH_ENV: /home/circleci/project/.bashrc
    steps:
      - checkout
      - run: sudo apt-get install -q -y ca-certificates
      - run: touch $BASH_ENV
      - run: echo 'export IMPORT_PATH=$GOPATH/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
      - run: git status -s
      - run: echo "export PROCESS_AGENT_VERSION=$(packaging/version.sh)" >> $BASH_ENV
      - run: echo "export EBPF=${EBPF:-true}" >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV && source $BASH_ENV
      - run: sudo apt-get update && sudo apt-get -y install linux-headers-$(uname -r) rsync rake
      - run: mkdir -p $GOPATH $GOPATH/bin $IMPORT_PATH download
      - run: test -e download/$GODIST || curl -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
      - run: sudo tar -C /usr/local -xzf download/$GODIST --mode='a+rwX'
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
      - run: rsync -azC --delete ./ $IMPORT_PATH
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: go get golang.org/x/lint/golint
      - run: printenv
      - run: go version
      - run: cd $IMPORT_PATH && rake ci
      - run: cd $IMPORT_PATH/packaging && ./apply_branding.sh
      - run: cd $IMPORT_PATH && rake build
      - run:
          name: Move compiled binaries to workspace
          command: |
            mkdir -p /tmp/workspace/binaries
            mv $IMPORT_PATH/process-agent /tmp/workspace/binaries
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - binaries

  package:
    docker:
      - image: circleci/ruby:2.4.4-stretch-node-browsers
    environment:
      - GOPATH: /home/circleci/project/.go_workspace
      - BASH_ENV: /home/circleci/project/.bashrc
    steps:
      - run: sudo apt-get install -y -q rsync rpm s3cmd
      - *attach_workspace
      - *restore_repo
      - run: touch $BASH_ENV
      - run: git status -s
      - run: echo "export PROCESS_AGENT_VERSION=$(packaging/version.sh)" >> $BASH_ENV
      - run: echo "export EBPF=${EBPF:-true}" >> $BASH_ENV
      - run: echo 'export IMPORT_PATH=$GOPATH/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV && source $BASH_ENV
      - run: rsync -azC --delete ./ $IMPORT_PATH
      - run:
          name: Restore compiled binaries from workspace
          command: |
            set -exu
            mv /tmp/workspace/binaries/* $IMPORT_PATH
      - run: gem install --no-ri --no-rdoc fpm
      - run: gem install --no-ri --no-rdoc deb-s3
      - run: ls -la $IMPORT_PATH
      - run: ls -la $IMPORT_PATH/packaging
      - run: cd $IMPORT_PATH/packaging && ./build_staging_package.sh
      - run: cd $IMPORT_PATH/packaging && ./publish_staging_package.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package:
          requires:
            - build
