//go:build !windows
// +build !windows

package config

const (
	defaultLogFilePath = "/var/log/datadog/process-agent.log"

	// Agent 5
	defaultDDAgentPy    = "/opt/datadog-agent/embedded/bin/python"
	defaultDDAgentPyEnv = "PYTHONPATH=/opt/datadog-agent/agent"

	// Agent 6
	defaultDDAgentBin = "/opt/datadog-agent/bin/agent/agent"
)

// Process blacklist
var defaultBlacklistPatterns = []string{
	"^/usr/bin/stress",
	"^stress",
	"^/usr/bin/yes",
	"^yes\\s.*$",
	"^-bash",
	"^-sh",
	"^su\\s.*$",
	"^/lib/systemd/",
	"^/usr/lib/systemd/",
	"^pickup",
	"^/sbin/",
	"^/usr/sbin/.*",
	"^/usr/sbin/sshd",
	"^qmgr",
	"^sshd:",
	"^/usr/bin/vi(?:m|m.basic)?\\s",
	"^/usr/bin/tail",
	"^\\(sd-pam\\)",
	"^/compose-controller\\s",
	"^/api-server",
	"^containerd-shim",
	"^docker-container-shim",
	"^docker-containerd",
	"^docker-containerd-shim",
	"^pause",
	"^/pause",
	// Kubernetes / Containerized environments
	"^/usr/lib/accountsservice/accounts-daemon",
	"^/adapter",
	"^/sbin/agetty",
	"^/bin/alertmanager*",
	"^/usr/bin/amazon-ssm-agent",
	"^/usr/lib/at-spi2-core/at-spi-bus-launcher",
	"^/usr/lib/at-spi2-core/at-spi2-registryd",
	"^atlantis",
	"^avahi-daemon.",
	"^awk",
	"^/app/aws-k8s-agent",
	"^bash",
	"^/bin/bash",
	"^/usr/bin/bash",
	"^sh",
	"^/bin/sh",
	"^/usr/bin/sh",
	"^/bin/busybox",
	"^/usr/lib/bluetooth/bluetoothd",
	"^/app/cmd/cainjector/cainjector",
	"^calico-node",
	"^calico-typha",
	"^/bin/chaoskube",
	"^./cluster-autoscaler",
	"^/usr/lib/colord/colord",
	"^/configmap-reload",
	"^/usr/bin/containerd",
	"^/usr/local/bin/containerd",
	"^./controller",
	"^/coredns",
	"^crond",
	"^/usr/bin/dbus-daemon",
	"^/usr/lib/dconf/dconf-service",
	"^/sbin/dhclient",
	"^/usr/bin/dockerd",
	"^dotnet",
	"^.*dumb-init",
	"^/usr/bin/exporter",
	"^external-dns",
	"^/usr/lib/x86_64-linux-gnu/fwupd/fwupd",
	"^/usr/bin/ghostunnel",
	"^/usr/lib/gvfs/gvfsd-fuse",
	"^/usr/lib/gvfs/gvfsd",
	"^.*indicator-application/indicator-application-service",
	"^.*indicator-bluetooth/indicator-bluetooth-service",
	"^.*indicator-datetime/indicator-datetime-service",
	"^.*indicator-keyboard/indicator-keyboard-service",
	"^.*indicator-messages/indicator-messages-service",
	"^.*indicator-power/indicator-power-service",
	"^.*indicator-session/indicator-session-service",
	"^.indicator-sound/indicator-sound-service",
	"^/bin/IngressMonitorController",
	"^/sbin/init",
	"^lightdm",
	"^/usr/bin/lsmd",
	"^/sbin/lvmetad",
	"^/usr/libexec/postfix/master",
	"^nm-applet",
	"^/usr/lib/x86_64-linux-gnu/notify-osd",
	"^/bin/oauth2_proxy",
	"^/usr/lib/policykit-1/polkitd",
	"^/usr/bin/pulseaudio",
	"^rescheduler",
	"^/usr/lib/rtkit/rtkit-daemon",
	"^ruby",
	"^/usr/local/bin/ruby",
	"^runsv",
	"^/usr/bin/runsvdir",
	"^/home/weave/runsvinit",
	"^/bin/operator",
	"^s6-",
	"^sleep",
	"^/lib/systemd",
	"^tail",
	"^/tiller",
	"^/usr/bin/tini",
	"^tini",
	"^/usr/lib/udisks2/udisksd",
	"^.*unity-settings-daemon",
	"^/usr/bin/unpigz",
	"^/usr/lib/upower/upowerd",
	"^upstart",
	"^/app/cmd/webhook/webhook",
	"^/usr/bin/whoopsie",
	"^/sbin/wpa_supplicant",
	"^/usr/lib/xorg/Xorg",
	"^/usr/lib/snapd/snapd",
}
