#!/bin/sh -x

INSTALL_DIR=/opt/dd-process-agent
LOG_DIR=/var/log/dd-process-agent.log

getent group dd-agent >/dev/null || groupadd -r dd-agent
getent passwd dd-agent >/dev/null || \
useradd -r -M -g dd-agent -d $INSTALL_DIR -s /bin/bash -c "Datadog Agent" dd-agent

# set proper rights to dd-agent user
chown -R dd-agent:dd-agent ${INSTALL_DIR}
if [ -f $LOG_DIR ]; then
    chown -R dd-agent:dd-agent ${LOG_DIR}
else
    touch ${LOG_DIR}
    chown -R dd-agent:dd-agent ${LOG_DIR}
fi

echo "Adding dd-process-agent to start on boot..."
chkconfig --add dd-process-agent
