#!/bin/sh
#
# chkconfig: 345 85 15
# description: Datadog Process Agent

### BEGIN INIT INFO
# Provides: sts-process-agent
# Short-Description: Start and stop sts-process-agent
# Description: sts-process-agent is the process agent component for Datadog
# Required-Start: $remote_fs
# Required-Stop: $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

PIDFILE=/opt/sts-process-agent/run/sts-process-agent.pid
DAEMON=/opt/sts-process-agent/bin/sts-process-agent
CONFIG=/etc/dd-agent/sts-process-agent.ini
export DD_PROCESS_AGENT_ENABLED=true

# Source functions library.
. /etc/init.d/functions

makePid() {
    echo `ps auxf | grep -v grep | grep $1 | awk '{print $2}'` > $PIDFILE
}

start() {
    # no need to test for status before daemon,
    # the daemon function does the right thing
    if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            echo sts-process-agent already running: $PID
            exit 2;
    else
        echo "Starting sts-process-agent"
        daemon --pidfile $PIDFILE --user dd-agent "exec $DAEMON -config=$CONFIG >> /var/log/sts-process-agent.log 2>&1 &"
        [ $? -eq 0 ] && makePid $DAEMON
    fi
    echo
    return $?
}

stop() {
    # no need to test for status before killproc,
    # it does the right thing. and testing supervisorctl status
    # before killproc can lead to states where you cannot stop!
    echo -n 'Stopping sts-process-agent (using killproc): '
    killproc -p $PIDFILE -d 30
    echo
    return 0
}

restart() {
    stop
    start
}

case "$1" in
   start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        restart
        ;;

    status)
        status -p "$PIDFILE" sts-process-agent
        ;;

esac

exit $?
